 # Clase 1 - Python

## Contenido

- Introducción y herramientas
- Utilidades y tipos de datos
- Numpy
- Basics de Análisis de Datos



# Introducción y herramientas

## ¿Qué es Python?
- Desarrollado por Guido Van Rossum
- De propósito general: puedes construir lo que quieras
- Open source, es decir, es *gratis*
- Lenguaje orientado a objetos: todo es un objeto
- Es fácil hacer paquetes para Python, también para Ciencia de Datos
- Vamos a ver Python enfocado a Ciencia de Datos
    - Cómo guardar datos
    - Cómo limpiar datos
    - Cómo manipular datos
    - Herramientas para análisis
- Hay muchas versiones de Python, vamos a trabajar con la 3.7
    - Solamente si van a trabajar con [Theano](http://deeplearning.net/software/theano/) recomienda la 2.7


## ¿Cómo vamos a trabajar?
- Bajar [Anaconda](https://www.anaconda.com/)
- Bajar [Jupyter](http://jupyter.org/)
- Bajar [Spyder](https://www.spyder-ide.org/)
- Shell de Python:
    - Es como la consola de R
    - Permite escribir código para experimentar
- Scripts:
    - Son archivos de texto reproducibles, tienen la extensión *.py*
    - Contienen una serie de comandos en Python
    - Similares a escribir en el shell de IPython
- Jupyter Notebook
    - Es un cuaderno que nos permite combinar tanto texto como código
    - El texto está escrito con formato Markdown igual que RMarkdown :)
- Spyder
    - Muy parecido a RStudio pero para Python
    - Es uno de los IDES más populares

### ¿Qué es Anaconda?

- Es una distribución de Python y de R, la más famosa para Ciencia de Datos
- 6 millones de usuarios que hacen ciencia de datos
- Estándar de la industria para desarrollar, probar y entrenar modelos en una sola máquina
- Permite la colaboración de muchos usuarios en tiempo real
- Permite crear ambientes con versiones específicas de Python y paquetes instalados: ENCAPSULAMIENTO
- Esto es un súper plus en Python porque tenemos muchas versiones diferentes que son compatibles con algunos paquetes pero no con otros
- Es fácil crear una seria de paquetes y versiones que sean distribuibles, i.e. que pueda compartir con otros usuarios, incluyendo todas sus dependencias
- Cuando instalamos Anaconda, podemos crear un ambiente y ponerle la versión de Python que queramos
- Anaconda ya tiene precargados el NoteBook de Jupyer y otros paquetes para ciencia de datos

#### Cómo usamos Anaconda

- Creación de [ambientes](https://conda.io/docs/user-guide/tasks/manage-environments.html#activate-env)

1. Para crear un ambiente de cierta versión de Python:

`conda create -n myenv python=3.4`

2. Para instalar un paquete

`conda install -n myenv scipy`
.
    - Si queremos una versión específica del paquete: 
    
  `conda install -n myenv scipy=0.15.0`
     
3. Si queremos instalar de una vez Python con ciertos paquetes

`conda create -n myenv python=3.4 scipy=0.15.0 astroid babel`

4. Si queremos clonar un ambiente:

`conda create --name myclone --clone myenv`

5. Para activar un ambiente

    - Windows: `activate myenv`
    - macOS y Linux: `source activate myenv`
    
6. Desactivar un ambiente:

    - Windows: `deactivate`
    - macOS y Linux: `source deactivate`

7. Para ver listado de ambientes

`conda info --envs`

8. Para saber qué ambiente está corriendo, me fijo en el que tiene el asterisco

`conda info --envs`

9. Para saber qué paquetes tiene instalados un ambiente

`conda list -n myenv`

10. Para saber qué paquetes tiene instalados mi ambiente corriendo

`conda list`

11. Para usar el comando `pip` (para instalar paquetes en Python), usamos:

`conda install -n myenv pip
source activate myenv
pip <pip_subcommand>`

12. Para eliminar un ambiente

`conda remove --name myenv --all`

> **EJERCICIO.** Crear un ambiente con Python 3.7 en Anaconda, instálale el paquete `pip` y finalmente actívalo. Cerciórate que ese nuevo ambiente está instalado.


### ¿Qué es el Notebook de Jupyter?

- [Jupyter Notebook](http://jupyter.org/) es una aplicación web libre que permite crear y compartir documentos con texto,código, ecuaciones, visualizaciones
- Se usa principalmente para hacer ciencia de datos (limpieza, transformación, modelado estadístico, machine learning, simulación, visualización)
- Puedes embeber código, gráficos, urls, videos y texto usando como sintaxis markdown
- Se puede usar con:
    - Python
    - Julia
    - R
    - C++
    - Scala
- Features:
    - Trabaja con varios lenguajes
    - Puedes compartir los notebooks por email, Dropbox, GitHub y el Jupyter Notebook Viewer
    - Output interactivo: HTML, images, videos, LaTeX
    - Integración con herramientas de Big Data de Apache Spark desde Python (Pyspark, la API de Python para Spark),  R  (Sparklyr) y Scala. Es decir, se puede explorar lo mismo con pandas, scikit-learn, ggplot2, Tensorflow
    - Se puede exportar en muchos formatos:
            - html
            - .ipynb (notebook)
            - pdf
            - LaTex
    


#### ¿Cómo instalamos Jupyter?

Para tener *Jupyter*, necesitamos tener Python>=3.3 o Python 2.7

2 maneras:

- Usando *Anaconda*, que ya trae Python y Jupyter 
- Usando `pip`python3 -m pip install --upgrade pip. `pip` es el manejador de paquetes de Python, con ese comando instalaremos los paquetes.

`python3 -m pip install jupyter`


#### ¿Cómo abrimos un notebook de Jupyter?

- Simplemente creamos nuestro ambiente de Python en Anaconda, y escribimos `jupyter notebook`. Se nos abrirá un *Jupyter* con 

- Si no instalamos *Anaconda*, entonces simplemente ponemos `jupyter notebook` en la terminal

- ¿Cómo comparto mi notebook de Python?

#### ¿Cómo corremos los chunks de código en un notebook de Jupyer?

- Una caja de texto o código se corre de varias maneras:
- Individualmente pulsando el botón *Run* o `Shift+Enter`
- Individualmente en el menú *Cell*
- Todas con el menú `Cell` con la opción *Rull all*
- Opciones customizables usando el menú *Cell*

#### ¿Cómo compartimos nuestro notebook de Jupyter?

1. Hostear tu notebook de Python en un repo de Github. Esto tiene la ventaja de que está montado en la red.
    - Ir [NBViewer](http://nbviewer.ipython.org/) y pegar el URL de Github
ó

2. Email ó

3. Dropbox

4. Al parecer aún no se puede hostear en Bitbucket. Se supone que esto es una aplicación para hacerlo: [aplicación](https://bitbucket.org/bitbucket/bitbucket-nbviewer/src/master/)

>**EJERCICIO.** Dentro de tu ambiente de Python que creaste, abre un notebook de Jupyter, escribe tu nombre y expórtalo como Notebook .ipynb. Observa que también puedes ver tus proyectos de R en el mismo notebook de Jupyter pero observa también que todo esto está en ambiente local.

>**EJERCICIO. ** Hostea tu Notebook en [NBViewer](http://nbviewer.ipython.org/). Hint: Debes abrir una [cuenta en Github](https://reproducible-science-curriculum.github.io/sharing-RR-Jupyter/01-sharing-github/)

### ¿Qué es Spyder?
- [Spyder](https://www.spyder-ide.org/) es un IDE (Integrated Development Environment) escrito para trabajar con Python
- Está orientado al cómputo científico
- Es muy parecido a RStudio, así que será sencillo usarlo
- Viene con un editor para escribir código, una consola para evaluar y ver resultados
- También viene con una vista de variables para ver las que se han usado
- Otra opción de editor es [Pycharm](https://www.jetbrains.com/pycharm/), sin embargo esta IDE es mucho más compleja y está más orientada a Desarrolladores

>**EJERCICIO**. Abre Spyder desde la consola, crea un archivo que imprima tu nombre: `print("My nombre es ...")` y córrelo en la consola.


### Resumen

![](software_python.png)

## Utilidades y tipos de datos 

### Preliminares
- Comentarios se escriben con `#`
- Python puede usarse como calculadora:
    - Exponenciación: 2**4
    - Módulo: `5%2`
- Declaración de variables se hacen con `=`
- Ayuda de pide con `help()`
- Ver en qué versión de Python estás trabajando: `sys.version_info`. Verifica que es la 3.7

In [106]:
import sys 
sys.version_info

sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)

In [107]:
print("Así declaramos una variable: ")

x=2

print("\n")
print("Y la imprimimos: ")
print(x)

Así declaramos una variable: 


Y la imprimimos: 
2


### Tipos básicos

- Tipos de datos
    - `int`: enteros
    - `float`: punto flotante, tiene parte entera y decimal separada por punto
    - `str`: strings
    - `bool`: booleanos
- Cada tipo tiene una funcionalidad distinta asociada
- El tipado en Python es *dinámico*, lo cual significa que el tipo de variable no tiene que ser declarado al inicio, pues el tipo de variable se conoce hasta que se corre el código
- Para saber el tipo de variables: `type()`

In [108]:
print("Enteros: ")
type(5)

Enteros: 


int

In [109]:
print("Floats: ")
#float
type(1.10)

Floats: 


float

In [110]:
print("Strings tenemos dos maneras de escribirlos: ")
print("hola")
print('hola')
print(type("hola"))

print("Los tipos de datos se comportan diferente")
"se"+"pega"*10

Strings tenemos dos maneras de escribirlos: 
hola
hola
<class 'str'>
Los tipos de datos se comportan diferente


'sepegapegapegapegapegapegapegapegapegapega'

### Cast
- `int()`
- `float()`
- `bool()`
- `str()`

### Asignación de variables
- Es por *referencia*, no por *valor* (recordar que en R es por *valor*)

In [111]:
print("Asigno a x una lista")
x = [1,2,3]
print(x)

print("\n")
print("Ahora guardo en y lo que estaba en x")
y = x

print("\n")
y[0] =100
print("Ahora modifico la primer entrada de y en " + str(y[0]))



print("\n")
print("Imprimo x y me doy cuenta que el valor también cambió")
print("Esto es porque la asignación es por referencia, no por valor")
print(x)

print("\n")
print("Ahora si en vez de lo anterior convierto a lista:")
y=list(x)

y[0]=1000000
print("Vuelvo a modificar la primer entrada de y en " + str(y[0]))
print("ahora 'y' es " + str(y))

print("\n")
print("Pero el valor de x no se modifico, ¿por qué?")

print(x)

Asigno a x una lista
[1, 2, 3]


Ahora guardo en y lo que estaba en x


Ahora modifico la primer entrada de y en 100


Imprimo x y me doy cuenta que el valor también cambió
Esto es porque la asignación es por referencia, no por valor
[100, 2, 3]


Ahora si en vez de lo anterior convierto a lista:
Vuelvo a modificar la primer entrada de y en 1000000
ahora 'y' es [1000000, 2, 3]


Pero el valor de x no se modifico, ¿por qué?
[100, 2, 3]


### Impresión
- Se hace usando `print()`
- Si se van a imprimir varios tipos de datos, se tiene que hacer *cast* a string antes 

In [112]:
x = 20
print("Hola, tengo " + str(x) + " años")

Hola, tengo 20 años


In [113]:
print(x+30, x, 10)


50 20 10


In [114]:
True+False

1

> **EJERCICIO.** ¿Cómo difiere Python de R con respecto a la forma de impriir?

### Listas
- Otro tipo de dato
- Sintaxis: `[x, y, z]`
- Colleción de valores
- Pueden tener cualquier tipo de dato (incluso listas!)
- Con `len` puedo ver su longitud

In [115]:
my_lista  = ["hola", "tengo", 10, ["años", "y contanto"]]
print(my_lista)
print(len(my_lista))

['hola', 'tengo', 10, ['años', 'y contanto']]
4


#### Acceso a listas:

    - Indexación: se hace usando `[]` al elemento que queremos accesar. 
        - Se empieza por *cero*, es decir `[0]` es el primer elemento
        - Podemos accesar al último elemento usando `[-1]`
    - Rangos: para obtener un subconjunto de la muestra, se hace usando `[inicio: final]`
        - El inicio es inclusivo, el final es exclusivo, es decir, el final no se incluye
    - Manipulación:
        - Cambiar elementos: simplemente uso `[]` para acceder a los elementos
        - Añadir elementos: lo agrego usando `+` y el elemento a añadir en corchetes
        - Eliminar elementos: uso `del[elemento]`

In [116]:
print(my_lista[0])
print(my_lista[-1])

print(my_lista[0:2])
print(my_lista[:3])
print(my_lista[-3:])

print(my_lista[0:])

my_lista[2] = 20
my_lista[0:2] =["ya", "cambié"]
print(my_lista)

print(my_lista + ["a lo seguro"])

del(my_lista[0])
print(my_lista)

hola
['años', 'y contanto']
['hola', 'tengo']
['hola', 'tengo', 10]
['tengo', 10, ['años', 'y contanto']]
['hola', 'tengo', 10, ['años', 'y contanto']]
['ya', 'cambié', 20, ['años', 'y contanto']]
['ya', 'cambié', 20, ['años', 'y contanto'], 'a lo seguro']
['cambié', 20, ['años', 'y contanto']]


### Operadores
- Booleanos se escriben con letras *and, or, not*
- Operadores `<,>,>=,<=,==,!=`

In [117]:
v1=True
v2=False
print(v1 and v2) 
print(v1 or v2)  
print(not v1)
print(5>6)

False
True
False
False


### Funciones

- Como en Matemáticas y se mandan llamar así `output = nombre_funcion(input)`
- `max()`, `round()`, `min()`

In [118]:
print(max([1, 378, 26, 8])), print(round(1.56)); print(round(1.56, 1))

378
2
1.6


> **EJERCICIO.** Crea un vector y normalízalo (i.e. que todos los valores queden entre 0 y 1). Después veremos otra manera de normalizar.

### Métodos
- Todo en Python es objeto, tiene asociados métodos
- Los métodos funciones de los objetos
- Se mandan llamar llamar usando `.` antes del objeto
- Métodos comunes de listas: 
    - `.index("Fer")` me da el índice de un elemento que quiera buscar en mi lista
    - `.count("cuentame")` me da las veces que el elemento aparece en mi lista
    - `.append("agrégame")` me permite añadir al final de mi lista un elemento
    - `.remove("elimíname")` me permite remover el primer elemento que cumple con el patrón dado
    - `.reverse` me pone el orden al revés
- Métodos comunes de strings:
    - `.capitalize()` me pone la primer letra de mi string en mayúscula
    - `.replace("ap", "rep")` me remplaza todas las ocurrencias de "ap" en mi lista por "rep"
    
- ¿Cómo saber qué strings hay para un tipo de dato? -> usamos `?`

In [119]:
print(my_lista)
my_lista.index(20)

['cambié', 20, ['años', 'y contanto']]


1

In [120]:
my_lista

['cambié', 20, ['años', 'y contanto']]

>EJERCICIO. Crea una lista y aplica cada una de las funciones de arriba

### Paquetes
- Son como scripts
- Tienen definidas funciones y métodos
- Se tienen miles de paquetes. Los hay para ciencia de Datos y son los que veremos como:
    - **Numpy:** manejar arreglos
    - **Matplotlib:** visualización
    - **Scikit-learn:** machine learning
- Instalar:
    - pip, un manejador de paquetes. Ir [aquí](https://pip.readthedocs.io/en/stable/installing/) y bajar `get-pip.py`
    - Ejecutar `get-pip.py` en la terminal y así podemos usar `pip` para instalar paquetes
- Importar paquete: `import nombre_paquete` -> esto importa toda la funcionalidad del paquete
- Hay que dar alias al paquete para llamarlo `import numpy as np`
- Si sólo queremos una función específica del paquete podemos usar: `from numpy import array`

In [121]:
import numpy as np

#array([10,30,40]) marca error porque el método del paquete se debe llamar

print("\n")
print("Imprimimos arreglo:")
print("\n")
print(np.array([10,30,40]))



Imprimimos arreglo:


[10 30 40]


In [122]:
from numpy import array

print("\n")
print("Si importamos 'array' igual nos imprime lo mismo")
print("\n")
print(array([10,30,40]))



Si importamos 'array' igual nos imprime lo mismo


[10 30 40]


## NumPy
- Las listas son potentes pero no es posible aplicar muchas operaciones matemáticas sobre ellas
- **NumPy** viene de "numeric Python"
- La arternativa a las listas es el "NumPy array", una librería de Python muy optimizada
- Se pueden hacer cálculos matemáticos sobre arreglos enteros fácil y rápidamente
- Desventaja vs listas: no se pueden guardar varios tipos de datos. Si se guardan diferentes entonces se hace *coerción*
- Sin embargo, NumPy es muy rápido justo gracias a que sólo guarda un tipo de dato
- Instalación: `pip install numpy`
- Se accesa igual que a las listas, usando `[]`


In [123]:
import numpy as np
vec1 = np.array([1,2,3,4,5])

print("El vector construido es: ")
print(vec1)

print("\n")
print("Podemos hacer operaciones aritméticas sobre él:")
print(vec1*3**2)

print("\n")
print("Sin embargo no es posible guardar varios tipos de datos:")
print(np.array([100, "Fer", False]))

print("\n")
print("Pero sí es posible sumar arrays: ")
print(np.array([30, 40, 55]) + np.array([20, 25, 16]))

print("\n")
print("Y accesar a sus componentes usando corchetes: ")
print(vec1[1])

print("\n")
print("Veamos qué entradas son mayores que 3")
print(vec1>3)

print("\n")
print("Y a qué elementos corresponden")
print(vec1[vec1>3])

El vector construido es: 
[1 2 3 4 5]


Podemos hacer operaciones aritméticas sobre él:
[ 9 18 27 36 45]


Sin embargo no es posible guardar varios tipos de datos:
['100' 'Fer' 'False']


Pero sí es posible sumar arrays: 
[50 65 71]


Y accesar a sus componentes usando corchetes: 
2


Veamos qué entradas son mayores que 3
[False False False  True  True]


Y a qué elementos corresponden
[4 5]


Operaciones útiles:


In [124]:
#Imprimir los números pares
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr % 2 == 0])

#Posiciones en común
v1 = np.array([1,2,3,2,3,4,3,4,5,6])
v2 = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(v1 == v2))

# Imprimir solo los números que están en cierto rango
a = np.arange(20)
print(a)
a[(a >= 10) & (a <= 20)]

#Stack dos vectores verticalmente
v1 = np.arange(10).reshape(2,-1)
v2 = np.repeat(1, 10).reshape(2,-1)

print(np.hstack([v1, v2])

#Stack dos vectores horizontalmente
#print(np.vstack([v1, v2]))
      
#Encontrar la intersección de dos vectores
v1 = np.array([1,2,3,4,5,6])
v2 = np.array([6,7,10,2,7,4,9,4,9,8])
print(np.intersect1d(v1,v2))

#Diferencia de dos vectores
print(np.setdiff1d(v1,v2))

#posiciones en donde los vectores son iguales      
print(np.where(v1 == v2))
      

SyntaxError: invalid syntax (<ipython-input-124-56d64489aa56>, line 24)

> **EJERCICIO.** Calcula los siguientes vectores:

In [ ]:
#Ahora remplaza los números pares por el valor -1000 (hint: igual que en R)

#Encuentra los números impares y reemplaza por -1

#Escribe un vector y normalízalo (i.e. que sus entradas queden entre 0 y 1). Hint: usa el método max() y el min()

#Ahora reemplaza todas las entradas que sean mayores o iguales que 0.5 por 1 y las que sean menores por -1

### 2d-dimensional arrays
- Se pueden crear con la misma sintaxis
- Con el método `.shape` se puede saber su dimensión
- No se pueden poner distintos tipos de datos
- Indexación se hace igual
- Es fácil indexar con `[m,n]` que con `[m][n]`

In [ ]:
vec2d = np.array([[1, 2, 3],[4, 5, 6]])

print("El vector construido es: ")
print(vec2d)

print("\n")
print("Su dimensión es: ")
print(vec2d.shape)

In [ ]:
print("La primera entrada es: ")
print(vec2d[0])

print("\n")
print("El tercer elemento de la primera entrada es:")
print(vec2d[0][2])

print("\n")
print("El elemento segundo de las dos entradas son")
print(vec2d[ :, 1:2])

print("\n")
print("La segunda entrada es:")
print(vec2d[1, :])


## Basics de análisis de datos

- Igual que en R, es importante tener estadísticas de resumen: media, mediana, desviación estándar, correlaciones
- NumPy tiene muchas funciones predefinidas con este propósito
- Se puede generar cualquier variable aleatoria, ver [documentación](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)


In [ ]:
muestra_normal = np.random.normal(0, 1, 10000)
muestra_exp = np. random.exponential(5, 10000)

vecsim = np.column_stack((muestra_normal, muestra_exp ))

print("\n")
print("El vector de normales y exponenciales simuladas es: ")

print("\n")
print(vecsim)

print("\n")
print("Resultados normal: ")
print("La media es " + str(np.mean(vecsim[:,0])))
print("La mediana es " + str(np.median(vecsim[:,0])))
print("La desviación estándar es " + str(np.std(vecsim[:,0])))


print("\n")
print("Resultados exponencial: ")
print("La media es " + str(np.mean(vecsim[:,1])))
print("La mediana es " + str(np.median(vecsim[:,1])))
print("La desviación estándar es " + str(np.std(vecsim[:,1])))

print(np.corrcoef(vecsim[0,:], vecsim[1,:]))

In [ ]:
print("El tamaño del arreglo es: ")
vecsim.shape

In [ ]:
print("\n")
print("Y así se ve: ")
print("\n")
print(vecsim)


In [ ]:
print("La muestra de normales: ")
vecsim[:,0]


In [ ]:
print("La muestra de exponenciales: ")
vecsim[:,1]


## Visualización
- Existen varios paquetes para visualización, pero el estrella es `matplotlib`
- Permite hacer gráficos de líneas, de dispersión, 
- Permite cambiar escala de los ejes `plt.xscale('log')`

### Gráfico de líneas

- Útil para series de tiempo
- Nos ayuda a ver tendencias

*Sintaxis:* `plt.plot(x, y)`

*Sintaxis:* Ejes con `plt.xlabel("eje x")`

*Sintaxis:* Ejes con `plt.ylabel("eje y")`

*Sintaxis:* Ejes con `plt.ylabel("titulo")`


In [ ]:
import matplotlib.pyplot as plt

plt.plot(vecsim[0:100, 0], vecsim[0:100, 1])
plt.xlabel("Simulaciones normales")
plt.ylabel("Simulaciones exponenciales")
plt.title("Simulaciones normales vs exponenciales")
plt.show()

### Gráfico de dispersión

- Nos sirve para ver la relación entre dos variables numéricas
- Nos ayuda a ver una posible correlación 

*Sintaxis:* `plt.scatter(x, y)`

*Argumentos:* `scatter(x, y)`

*Sintaxis:* `plt.yticks([...])` o bien `plt.yticks([...], [names])` para poner un nombre a los ticks

*Sintaxis:* `range(inicio, fin, paso)`. Ojo, el fin es exclusivo, se detiene uno antes.



In [ ]:
help(plt.scatter)
plt.xscale('log')
plt.scatter(vecsim[0:100, 0], vecsim[0:100, 1])
plt.yticks([range(0, 10, 2)])
plt.yticks([0,2,4,6,8,10], ['0e','2e', '3e', '4e', '5e','6e'])
plt.show()

### Histograma

- Nos ayuda a ver distribución de UNA variable numérica

*Sintaxis:* `plt.hist(x, y)`

*Argumentos:* `hist(x, bins=None)`

- `plt.clf()` nos ayuda a limpiar para poder plotear otra cosa. Si no lo hacemos y ponemos enseguida otra gráfica, las encimará.

In [ ]:
print("\n")
print("Si no le damos el número de bins, el default es 10")


plt.hist(vecsim[0:100, 0])
plt.show()



In [ ]:

plt.clf()
print("\n")
print("Ahora le damos un número de bins de 20")

plt.hist(vecsim[0:100, 0], 20)
plt.show()



In [ ]:

plt.clf()
print("\n")
print("Ahora le damos un número de bins de 5")
plt.hist(vecsim[0:100, 0], 5)
plt.show()